[project]
name = "monkeys"
version = "0.0.0"
description = "Utilities and templates for CI/testing demos."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11,<3.15"
keywords = ["templates", "ci", "testing"]
authors = [
  { name = "Thomas Schmelzer" }
]

# No runtime dependencies for this template repo
dependencies = []

[dependency-groups]
dev = [
	"marimo>=0.18",
	"pandas>=2.3",
	"numpy>=2.4",
        "plotly>=6.5",
        "polars>=1.3",
	"cvxsimulator>=1.4"
]

[project.urls]
repository = "https://github.com/tschm/monkeys"
homepage = "https://tschm.github.io/monkeys/book"
