[project]
name = "monkeys"
version = "0.0.0"
description = "Utilities and templates for CI/testing demos."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11,<3.15"
keywords = ["templates", "ci", "testing"]
authors = [
  { name = "Thomas Schmelzer" }
]

# No runtime dependencies for this template repo
dependencies = []

[project.urls]
repository = "https://github.com/tschm/monkeys"
homepage = "https://tschm.github.io/monkeys/book"


[project.optional-dependencies]
dev = [
    "pytest-cov==7.0.0",
    "pytest-html==4.1.1",
    "pytest==9.0.1",
    "pre-commit==4.5.0",
]
